# Generated by Django 5.0.4 on 2024-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo1", models.CharField(max_length=100)),
                ("campo2", models.CharField(max_length=100)),
            ],
        ),
    ]
